#!/bin/bash

#########################################################
#
# sway_monitor
#
# Control monitor configuration in sway
#
# Requires:
#  - rofi
#  - jq
#  - swaymsg
#
#########################################################

export BEMENU_BACKEND=wayland

MENU="rofi -dmenu -l 5 -no-custom"

get_modes() {
    NAME="$1"
    swaymsg -t get_outputs | jq -r '.[] | select(.name == "'$NAME'") | .modes[] | "\(.width)x\(.height) (\(.refresh))"'
}

set_mode() {
    NAME="$1"
    MODE="$2"
    swaymsg output "$NAME" mode "$MODE"
}

MONITOR=$(swaymsg -t get_outputs \
    | jq -r '.[] | "\(.name):\t\(.make) \(.model) (\(.current_mode.width)x\(.current_mode.height))"' \
    | $MENU -p 'Monitors' | cut -d':' -f1)

[ -z "$MONITOR" ] && exit 1
MODE=$(get_modes "$MONITOR" \
    | $MENU -p 'Modes' \
    | cut -d'(' -f1)

[ -z "$MODE" ] && exit 1
set_mode "$OUTPUT" "$MODE"
