# Commands go through bash
shell = "bash -c '{}'"

[[items]]
file = "~/.config/alacritty/theme.yml"
template = "alacritty"
subtemplate = "default-256"
rewrite = true

#[[items]]
#file = "~/.config/bat/config"

[[item]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true

[[item]]
file = "~/.themes/FlatColor/colors2"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
rewrite = true

[[items]]
file = "~/.config/mako/config"
template = "mako"
subtemplate = "custom"
hook = "systemctl --user restart mako"

[[items]]
file = "~/.config/sway/theme"
template = "sway"
subtemplate = "colors"
rewrite = true
hook = "swaymsg reload"
# Swaymsg reload temporarily freezes input, so it's marked as not light
light = false

[[item]]
file = "~/.config/waybar/theme.css"
template = "waybar"
hook = "pkill -SIGRTMIN+7 waybar"
rewrite = true
